spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    generic-properties:
      properties:
        historyTimeToLive: P1D